apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-indexfile
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  index.html: |
    {{ .Values.configMap.indexPageValue | default "Hello World" }}
